# Generated by Django 2.1.7 on 2020-07-09 07:22

from django.db import migrations, models
import teacher.validation


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200708_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.CharField(max_length=200, validators=[teacher.validation.subjects_taught_validator]),
        ),
    ]
