version: '2'
services:




  server:
    build:  .

    working_dir: /usr/src/app/
    command: python manage.py runserver 0.0.0.0:8888
    ports:
      - "8888:8888"
    volumes:
          - .:/usr/src/app/
    environment:
      - V=1
    networks:
      - default
#    depends_on:
#      - redis
#    links:
#      - redis